[project]
name = "turbogamma"
version = "0.0.1"
description = "Radiotherapy gamma index computation tool"
readme = "README.md"
authors = [
    { name = "gbo", email = "141006751+IfTrueEqualsEqualsTrue@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
turbogamma = "turbogamma:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
testpaths = ["tests"]